Add bottom navigation tab
t-analog/crowdfinder-client pull request #39
Opened 2021-11-28 14:57 UTC by psakurai

2021-11-29 07:27 UTC, mangkoran reviewed
For next commit, make sure to put the exact same name as the package name, e.g., `build: add @react-navigation/bottom-tabs`

2021-11-29 07:30 UTC, mangkoran requested changes
For `tab.js`, as it is a `component`, you may create new directory and put `tab.js` inside it.

2021-11-29 08:03 UTC, mangkoran commented on package.json
> +    "@react-navigation/bottom-tabs": "^6.0.9",
This is the only package you committed.

2021-11-29 08:06 UTC, psakurai commented on package.json
> +    "@react-navigation/bottom-tabs": "^6.0.9",
I haven't push the other 2 packages.

2021-11-29 08:06 UTC, mangkoran commented on package.json
> +    "@react-navigation/bottom-tabs": "^6.0.9",
Make sure to follow https://github.com/t-analog/crowdfinder-client/pull/39#pullrequestreview-817429076.

2021-12-01 01:02 UTC, mangkoran approved these changes

2021-12-01 01:02 UTC, mangkoran requested changes
Because since [this commit](https://github.com/t-analog/crowdfinder-client/pull/39/commits/de44b425e3678a1eeecc870f91c9b13ba5227c7d) you actually add another functionality unrelated to PR title.

2021-12-01 03:22 UTC, mangkoran approved these changes

2021-12-01 03:52 UTC, closed without merging