add profile screen
t-analog/crowdfinder-client pull request #63
Opened 2022-01-06 11:27 UTC by psakurai

2022-01-06 11:33 UTC, mangkoran requested changes

2022-01-06 11:33 UTC, mangkoran commented on screens/HomeScreen.js
> +    </View>
From line 5 until line 26 please mind the indentation.

2022-01-06 11:44 UTC, psakurai commented on screens/HomeScreen.js
> +    </View>
I had changed the code indentation.

2022-01-06 11:48 UTC, mangkoran commented on screens/HomeScreen.js
> +    </View>
The `return` line still left with wrong indentation. Please review the whole `return` block again.

2022-01-06 12:12 UTC, psakurai commented on screens/HomeScreen.js
> +    </View>
Done. Do I need to add space after line 28?

2022-01-06 12:23 UTC, mangkoran commented on screens/HomeScreen.js
> +    </View>
It's better if you could.

2022-01-06 12:23 UTC, mangkoran commented
May you snap a screenshot of the screen?

2022-01-06 12:41 UTC, psakurai commented on screens/HomeScreen.js
> +    </View>
Alright, I think can merge now.

2022-01-06 13:17 UTC, psakurai commented
> May you snap a screenshot of the screen?

![photo_2022-01-06_21-16-12](https://user-images.githubusercontent.com/76756035/148388660-82aafbc2-61b5-4a55-ac6a-10ff952a8ffc.jpg)

2022-01-07 15:19 UTC, mangkoran commented
After thinking for a while, could you update the layout based on penpot?

2022-01-08 01:50 UTC, mangkoran commented
I noticed that you create this PR based on `develop` branch. From now on, please make PR based on `develop-v2` branch and target `develop-v2` branch.

2022-01-08 01:50 UTC, closed without merging