Add drawer navigation
t-analog/crowdfinder-client pull request #67
Opened 2022-01-14 17:15 UTC by psakurai

2022-01-14 17:16 UTC, mangkoran requested changes
For icons please use @expo/vector-icons/Ionicons

2022-01-14 17:18 UTC, mangkoran requested changes
Please provide screenshot

2022-01-14 17:18 UTC, mangkoran commented on screens/SupportUs.js
> +export default SupportUs;
Create separate commit

2022-01-14 17:24 UTC, psakurai commented
![tab1](https://user-images.githubusercontent.com/76756035/149558247-a4f83878-827c-4a41-9ca9-914a79f9a734.jpg)
![tab2](https://user-images.githubusercontent.com/76756035/149558271-9a93c69b-675b-42a9-bf20-1d26fb35c255.jpg)

2022-01-14 17:29 UTC, mangkoran commented
Refer to the latest design on penpot. We won't use drawer for settings. We will use hamburger menu instead.

2022-01-17 15:35 UTC, psakurai commented
This PR will be closed due to unsupported modules.

2022-01-17 15:35 UTC, closed without merging